# Generated by Django 4.2.9 on 2024-01-23 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='prodyct',
            name='weight',
            field=models.IntegerField(default=0, verbose_name='Вес'),
        ),
    ]
